# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-30 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user_photo',
        ),
    ]
